openapi: 3.2.0
info:
  title: CollectOSS REST DEI Badging API
  version: 0.60.0
host: example.com
basePath: /api/unstable/
tags:
- name: DEI Badging
paths:
  /dei/repo/add:
    post:
      description: Add and start repo for DEI Badging
      operationId: DEI Badging Tracking
      parameters:
      - description: Client [API_Key]
        in: header
        required: true
        name: Authorization
        schema:
          type: string
        type: string
      - description: The source badging ID
        in: query
        required: true
        name: id
        schema:
          type: string
        type: string
      - description: The badging level
        in: query
        required: true
        name: level
        schema:
          type: string
        type: string
      - description: The repo URL to track
        in: query
        required: true
        name: url
        schema:
          type: string
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              status:
                type: string
                enum:
                - Success
                - Repo already exists
                - Error adding repo
                example: Success
        '400':
          description: Missing Argument
          schema:
            type: object
            properties:
              status:
                type: string
                enum:
                - Missing argument
      tags:
      - DEI Badging
      summary: DEI badging tracking
      x-summary-source: derived
  /dei/report:
    post:
      description: Request the report for the given badging project. On success, the report PDF will be returned in a Binary response. On failure, a JSON response with a status will be returned.
      operationId: DEI Badging Report
      parameters:
      - description: Client [API_Key]
        in: header
        required: true
        name: Authorization
        schema:
          type: string
        type: string
      - description: The source badging ID
        in: query
        required: true
        name: id
        schema:
          type: string
        type: string
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              status:
                type: string
                enum:
                - Invalid ID
        '400':
          description: Missing Argument
          schema:
            type: object
            properties:
              status:
                type: string
                enum:
                - Missing argument
      tags:
      - DEI Badging
      summary: DEI badging report
      x-summary-source: derived
externalDocs:
  description: CHAOSS Metric Definitions
  url: https://chaoss.community/kb-metrics-and-metrics-models/
